POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "daniyarmursza@gmais.com",
  "password": "Danik1234"
}

###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "email": "daniyarmursza@gmails.com",
  "password": "Danik1234",
  "jwtQuestion": "Kak dela",
  "jwtSecret": "horosho"
}

###
